# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
