# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import picture.utils


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20170606_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='type',
            new_name='content_type',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=picture.utils.PathAndRename('images/2017/06/07')),
        ),
    ]
